language: cpp
sudo: false
dist: xenial

git:
  depth: 3

cache:
  apt: true
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - libopenmpi1.10
      - openmpi-bin
      - openmpi-common

env:
  global:
    - SPACK_ROOT: $HOME/.cache/spack
    - PATH: $PATH:$HOME/.cache/spack/bin

before_install:
  - export CXX=g++
  - export CC=gcc
  - export FC=gfortran
  - export CXXFLAGS="-std=c++11"

install:
  - if ! which spack >/dev/null; then
      mkdir -p $SPACK_ROOT &&
      git clone --depth 50 https://github.com/platoengine/spack.git $SPACK_ROOT &&
      echo -e "config:""\n  build_jobs:"" 4" > $SPACK_ROOT/etc/spack/config.yaml;
    fi
  - spack clean -a
  - source /etc/profile &&
    source $SPACK_ROOT/share/spack/setup-env.sh
  - if [ ! -d $HOME/.spack ]; then
      mkdir $HOME/.spack;
    fi  
  - echo "packages:" > $HOME/.spack/packages.yaml
  - echo "    openmpi:" >> $HOME/.spack/packages.yaml
  - echo "        openmpi@1.10.2: /usr" >> $HOME/.spack/packages.yaml
  - echo "    buildable: False" >> $HOME/.spack/packages.yaml
  - cat $HOME/.spack/packages.yaml

script:
  - mkdir -p $HOME/build
  - cd $HOME/build
  - travis_wait 90 spack setup -v platoengine+unit_testing+platostatics+regression @master ^openmpi@1.10.2
  - ./spconfig.py $TRAVIS_BUILD_DIR
  - make -j 2
  - make test
